// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amdqwgfdzzsdwrkcgcvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtZHF3Z2ZkenpzZHdya2NnY3ZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNDg4MDgsImV4cCI6MjA5MDYyNDgwOH0.0f9qqwF79A0uqYuN0HgHYbkmW72opKE9dRnaN4qkCSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});